### ISSUE TITLE
Package get error

### ISSUE THREAD

**Issue by mccadi** [PonnamKarthik/FlutterHtmlView#1]
Hello! When attempting to get the plugin:

`dependencies:
  flutter_html_view: "^0.3.1"`

I get this error: "Package flutter_html_view has no versions that match >=0.3.1 <0.4.0 derived from:
- html_demo depends on version ^0.3.1"

Is it because I am using the newest beta of flutter? Thank you

**Comment by ponnamkarthik** [comment]
Can you list all the dependencies you are using

**Comment by mccadi** [comment]
There are no other dependencies aside from flutter html view. Sorry for late reply I was off on the weekend.

**Comment by ponnamkarthik** [comment]
Have you checked with new Version

```ymal
dependencies:
  flutter_html_view: "^0.4.0"
```

**Comment by mccadi** [comment]
No luck still. Here is output

"[html_demo] flutter packages get
Running "flutter packages get" in html_demo...
Package flutter_html_view has no versions that match >=0.4.0 <0.5.0 derived from:
- html_demo depends on version ^0.4.0
pub get failed (1)
exit code 1
"

and here is my pubspec.yaml:

I actually do have cupertino icons but it does not seem to conflict. Thanks.


[pubspecTEXT.txt](https://github.com/PonnamKarthik/FlutterHtmlView/files/1938420/pubspecTEXT.txt)

**Comment by ponnamkarthik** [comment]
can you copy paste the content of the file the file you sent is not in a readable format 

and 

can you paste the "flutter doctor" output

**Comment by mccadi** [comment]
Sure.

`name: html_demo
description: A new Flutter project.

dependencies:
  flutter_html_view: "^0.4.0"

  
  flutter:
    sdk: flutter
  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

    


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
 # assets:

  

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
`

**Comment by mccadi** [comment]
Sure.
```
name: html_demo
description: A new Flutter project.

dependencies:
  flutter_html_view: "^0.4.0"

  
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
```

**Comment by ponnamkarthik** [comment]
try 
```
flutter upgrade
```
and check

**Comment by mccadi** [comment]
It worked, thank you!
