### ISSUE TITLE
How do I change the text color without HTML in HtmlText

### ISSUE THREAD

**Issue by crazecoder** [PonnamKarthik/FlutterHtmlView#16]

**Comment by thenexus00** [comment]
Adding to this:
It would be good to be able to support a style parameter within the call:
`new HtmlView(
                  data: item.htmlBody, new TextStyle(fontWeight: FontWeight.bold) 
                )`

**Comment by The-Redhat** [comment]
I made a pull request which lets you wrap the HtmlView inside a DefaultTextStyle and specifiy the default text-color, fontWeigth, ... When html provides a value for the given attribute it overrides that.
