### ISSUE TITLE
Support onTap for images 

### ISSUE THREAD

**Issue by The-Redhat** [PonnamKarthik/FlutterHtmlView#17]
Hey it would be really nice if you could implement a feature to specifiy an onTap method for images.

**Comment by ghost** [comment]
You can add it, but you need to Fork. I asked for link taps too but the authour said its not possible. Its is possible...

**Comment by ponnamkarthik** [comment]
@gedw99 can you make a pull request for the changes you have done

**Comment by ghost** [comment]
hey @PonnamKarthik 
My fork has been subsumed into a larger project and the code and techniques for transcoding moved into golang from dart. Log story why, but to do with cross platform aspects of reusing the Web template DSL across web and flutter projects So i cant give you a PR for it. 

But i think its pretty easy to add to your existing code ?

**Comment by The-Redhat** [comment]
Since I moved to another library I will close this issue.
