### ISSUE TITLE
Cannot render an iframe

### ISSUE THREAD

**Issue by rubencg195** [PonnamKarthik/FlutterHtmlView#23]
Hi am trying to render the following url:

String html = '<iframe id="embedded-human" frameBorder="0" width="600" height="450" src="https://human.biodigital.com/widget/?m=production/maleAdult/atrial_fibrillation_heart_conduction_system_tour.json&initial.hand-hint=true&ui-info=true&ui-tour=[object object]&ui-zoom=true&ui-share=false&uaid=2nran"></iframe>';

but the screen appears blank. I tried with simple heading and images and worked fine.** The problem comes when trying to render iframes.**

**Comment by ponnamkarthik** [comment]
iframe is not supported 

some of the supported tags are p,img, h1..h6.b,s,
