### ISSUE TITLE
Video -> Source tag

### ISSUE THREAD

**Issue by marianoarga** [PonnamKarthik/FlutterHtmlView#32]
Could support for "source" tag inside video tag be added? I'm using this html layout and the plugin is not parsing it well since it looks for "src" attribute in the video tag only.

example:
https://www.w3schools.com/html/html5_video.asp
```
<video width="320" height="240" controls>
  <source src="movie.mp4" type="video/mp4">
  Your browser does not support the video tag.
</video>

**Comment by ponnamkarthik** [comment]
@marianoarga check latest version

**Comment by marianoarga** [comment]
Thank you, testing right now.
