### ISSUE TITLE
Can't use img tag and video tag

### ISSUE THREAD

**Issue by 0xBB2B** [PonnamKarthik/FlutterHtmlView#39]
![simulator screen shot - iphone x - 2018-08-23 at 11 21 01](https://user-images.githubusercontent.com/29423499/44501099-ba0dc480-a6c6-11e8-8b3e-24376e461c3b.png)

**Comment by NorthNarongrit** [comment]
same prob

**Comment by ponnamkarthik** [comment]
fixed in latest version 0.5.5
