### ISSUE TITLE
Both &nbsp; and literal char code 160 (\u00A0) are shown as "&nbsp;"

### ISSUE THREAD

**Issue by isoos** [PonnamKarthik/FlutterHtmlView#5]
_From @gregko on May 12, 2018 13:3_

URL: https://pub.dartlang.org/packages/flutter_html_view#-analysis-tab-

If the data string to show in HtmlView control contains "Some&amp;nbsp;text" or "Some_test", where underscore _ represents Unicode code point 160 '\00A0', the HtmlView shows literally:

`Some&nbsp;text
`

To avoid the issue I have to use code like:

`  s = s.replaceAll('\u00A0', ' ');
`
or 
`  s = s.replaceAll('&nbsp;', ' ');
`

_Copied from original issue: dart-lang/pub-dartlang-dart#1287_

**Comment by isoos** [comment]
@gregko: the current issue tracker is for the pub site, please use the package's repository for reporting issues.

**Comment by gregko** [comment]
Thank you for moving the issue to the correct place, I was confused about where to report such issues.

**Comment by ponnamkarthik** [comment]
fixed in v0.5.2
