### ISSUE TITLE
Version Fail for 0.5.8

### ISSUE THREAD

**Issue by shashkiranr** [PonnamKarthik/FlutterHtmlView#53]
Error - 

`Because every version of flutter_test from sdk depends on http 0.12.0 and flutter_cache_manager ^0.1.0-rc.1 depends on http ^0.11.3+14, flutter_test from sdk is incompatible with flutter_cache_manager ^0.1.0-rc.1.
And because flutter_html_view >=0.5.8 depends on cached_network_image ^0.4.2 which depends on flutter_cache_manager ^0.1.2, flutter_test from sdk is incompatible with flutter_html_view >=0.5.8.
So, because xx_project depends on both flutter_html_view ^0.5.8 and flutter_test any from sdk, version solving failed.`

Flutter version - 

`Flutter 0.10.1-pre.44 • channel master • https://github.com/flutter/flutter.git
Framework • revision bf92d7f286 (3 days ago) • 2018-10-15 13:46:25 -0700
Engine • revision 50c2e69daf
Tools • Dart 2.1.0-dev.7.0.flutter-b99bcfd309`

**Comment by ghost** [comment]
Have exactly the same issue also.

**Comment by hui00** [comment]
me2

**Comment by RedTo** [comment]
Any progress on this issue?

**Comment by l-k22** [comment]
same issue...

**Comment by nemanjalugi** [comment]
Same issue

**Comment by magillus** [comment]
see my PR: https://github.com/PonnamKarthik/FlutterHtmlView/pull/56 for work around

**Comment by ponnamkarthik** [comment]
Merged  PR: #56

**Comment by l-k22** [comment]
#56 just throws more compatibility issues for me.
