### ISSUE TITLE
flutter_html_view ^0.5.8, version solving failed.

### ISSUE THREAD

**Issue by sathishRA91** [PonnamKarthik/FlutterHtmlView#55]
no versions of flutter_html_view match >0.5.8 <0.6.0 and flutter_html_view 0.5.8 depends on cached_network_image ^0.4.2, flutter_html_view ^0.5.8 requires cached_network_image ^0.4.2.
And because no versions of cached_network_image match >0.4.2 <0.5.0 and cached_network_image 0.4.2 depends on flutter_cache_manager ^0.1.2, flutter_html_view ^0.5.8 requires flutter_cache_manager ^0.1.2.
Because flutter_cache_manager 0.1.2 depends on http ^0.11.3+14 and no versions of flutter_cache_manager match >0.1.2 <0.2.0, flutter_cache_manager ^0.1.2 requires http ^0.11.3+14.
Thus, flutter_html_view ^0.5.8 requires http ^0.11.3+14.
And because every version of flutter_test from sdk depends on http 0.12.0, flutter_html_view ^0.5.8 is incompatible with flutter_test from sdk.

**Comment by 85636682** [comment]
flutter:  v0.10.2
flutter_cache_manager: ^0.2.0
cached_network_image: ^0.5.0
```
Because every version of flutter_html_view from git depends on cached_network_image ^0.4.2 and swb_flutter_app depends on cached_network_image ^0.5.0, flutter_html_view from git is forbidden.
So, because swb_flutter_app depends on flutter_html_view from git, version solving failed.
```

**Comment by sathishRA91** [comment]
@85636682 solution?

**Comment by 85636682** [comment]
@sathishRA91 no，flutter_html_view  must update cached_network_image from  ^0.4.2 to ^0.5.0

**Comment by sathishRA91** [comment]
@85636682 ok thanks

**Comment by 85636682** [comment]
@sathishRA91 use flutter_html: ^0.8.2 instead it

**Comment by sathishRA91** [comment]
@85636682 Thanks its working fine
