### ISSUE TITLE
Please use MarkdownBody instead of Markdown

### ISSUE THREAD

**Issue by The-Redhat** [PonnamKarthik/FlutterHtmlView#74]
You cannot put Markdown in another list. So with MarkdownBody you are way more flexible.

**Comment by Eimji** [comment]
I agree with @The-Redhat !

**Comment by ponnamkarthik** [comment]
@The-Redhat and @Eimji Please use `scrollable: false` to use MarkdownBody

**Comment by Eimji** [comment]
Thansk :) I also found this new option after noticing that my code was broken using the latest version of your plugin. Great work for your plugin :)

**Comment by thgoebel** [comment]
@PonnamKarthik When will there be a new release, containing the `scrollable` parameter? I think it would fix an issue I've had as well, but as far as I [see](https://pub.dartlang.org/documentation/flutter_html_view/0.5.11/flutter_html_view/HtmlView-class.html) it's not yet in 0.5.11 (it only been [comitted](https://github.com/PonnamKarthik/FlutterHtmlView/commit/28988c589db9b780dd5a0f7420cefc47262721ed) the day after, hasn't it?). Thanks a lot for your plugin :)
