### ISSUE TITLE
HtmlView error in rendering <iframe>,  <blockquote>

### ISSUE THREAD

**Issue by Seedorf161** [PonnamKarthik/FlutterHtmlView#8]
HtmlView showing error when it encounters `<iframe>` and `<blockquote>` 

For the `<iframe>` it contains YouTube Video HTML embed code while the `<blockquote>` is Twitter's tweet and Instagram post HTML embed code in `<blockquote>.`

![screenshot_20180531-121704](https://user-images.githubusercontent.com/12864618/40781034-f3f31b80-64c9-11e8-98d4-df71103f9624.png)

**Comment by ponnamkarthik** [comment]
iframe, blockquote is not supported yet

**Comment by Seedorf161** [comment]
How soon should we be expecting the support?

And please is there any other way to achieve this? I'm new to flutter.

**Comment by ponnamkarthik** [comment]
support for iframe is cannot be implemented 

Please check updated [README.md](https://github.com/PonnamKarthik/FlutterHtmlView/blob/master/README.md)
