### ISSUE TITLE
List of supported tags ?

### ISSUE THREAD

**Issue by ghost** [PonnamKarthik/FlutterHtmlView#9]
Maybe make a little markdown doc in the repo to say what tags are supported and why ?

i was thinking that its impossible to suppot all tags.
then i was thinking that maybe its smart to support the MDC tags ? 

in the readme here ( https://github.com/material-components/material-components-web-components ), there is a link to this :

https://gist.githubusercontent.com/sorvell/2ec11ccde449815bc97edc1026be27a9/raw/8bab65dd5d15f657ae69493851690c5564367d13/index.html

As you can see they have fully qualified custom tags because its web components.

---

Now thats not everyone cup of tea and i can sympathise as web components brings along other dependencies.

in the core MDC repo here ( https://github.com/material-components/material-components-web), you can see in the demo folder the way the core MDC components are described.
For example Chips !
https://github.com/material-components/material-components-web/blob/master/demos/chips.html

Its using standard html tags with a special class to indicate what it should be.

---

Anyway maybe this is a smart way to align things ?
I bring this up because i like the idea id a data driven way to describe the layout and to be able to reuse it for web, flutter and print to PDF.

**Comment by ponnamkarthik** [comment]
Please check updated [README.md](https://github.com/PonnamKarthik/FlutterHtmlView/blob/master/README.md)
